/**
 * L2RecordsV2 ABI — loaded from contracts/abi/L2RecordsV2.json.
 *
 * DO NOT edit this file manually.
 * After changing the contract, run:   pnpm abi:sync
 *
 * Imported by:
 *   server/gateway/readers/L2RecordsReader.ts
 *   server/gateway/writer/L2RecordsWriterV2.ts
 *   workers/api/src/index.ts
 *   workers/gateway/src/index.ts
 *   src/admin.ts
 */
import type { Abi } from 'viem'
import abiJson from '../../contracts/abi/L2RecordsV2.json'

// JSON imports don't carry literal types; double-cast tells viem the ABI is valid.
export const L2RecordsV2ABI = abiJson as unknown as Abi
